name: example-environment
channels:
  - conda-forge
  - default
dependencies:
  - matplotlib
  - numpy=1.21.5
  - pandas
  - scipy>1.9.3
  - ipython
  - ipywidgets=7.6.5
  - ipympl=0.9.3
  - voila
  - xlrd
  - markdown
  