name: example-environment
channels:
  - conda-forge
  - default
dependencies:
  - matplotlib
  - numpy
  - pandas
  - scipy
  - ipython
  - ipywidgets <8.0.0
  - ipympl
  - voila
  - xlrd
  - markdown
  